[tool.poetry]
name = "GeVhoo_diff_calc"
version = "0.1.0"
description = "Difference calculator"
authors = ["GeVhoo <gvahrushev@mail.ru>"]
repository = "https://github.com/GeVhoo/python-project-lvl2"
packages = [
	{ include = "diff_calc" },
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
diff-calc = "diff_calc.gendiff:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
